USE Examende_Irvin_ROmero;

/* 1. */
SELECT NOMBRE
FROM CONDUCTORES
WHERE CATEGORIA = 18
  AND LOCALIDAD = 'ARGANDA';

/* 2. */
SELECT C.NOMBRE AS CONDUCTOR,
       C.LOCALIDAD,
       M.NOMBRE AS MAQUINARIA
FROM CONDUCTORES C
INNER JOIN TRABAJOS T ON C.[C#] = T.[C#]
INNER JOIN MAQUINAS M ON T.[M#] = M.[M#]
WHERE M.PRECIO_HORA >= 10;



/* 4. */
SELECT P.[P#] AS NUMERO_PROYECTO,
       P.DESCRIPCION AS NOMBRE_PROYECTO,
       P.CLIENTE,
       M.NOMBRE AS MAQUINARIA,
       P.LOCALIDAD,
       T.FECHA,
       (T.TIEMPO * M.PRECIO_HORA) AS COSTO
FROM PROYECTOS P
INNER JOIN TRABAJOS T ON P.[P#] = T.[P#]
INNER JOIN MAQUINAS M ON T.[M#] = M.[M#]
WHERE M.NOMBRE = 'VOLQUETE'
  AND P.LOCALIDAD = 'RIVAS'
  AND (T.TIEMPO * M.PRECIO_HORA) > 500;


  /* 3.*/
SELECT T.[P#], P.LOCALIDAD, M.NOMBRE, T.FECHA
FROM TRABAJOS T
INNER JOIN PROYECTOS P ON T.[P#] = P.[P#]
INNER JOIN MAQUINAS M ON T.[M#] = M.[M#]
WHERE M.NOMBRE = 'VOLQUETE';
